import Fuse from 'fuse.js'
import type { ToolMeta } from '@toolbox/types/tool'

export const toolRegistry: ToolMeta[] = [
  // ─── Phase 1: 高频工具首批 (15个) ───────────────────────────────────────────

  // Format - 格式化
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    nameEn: 'JSON Formatter',
    description: '格式化、压缩、校验 JSON 数据，支持语法高亮，缩进可选',
    category: 'format',
    tags: ['json', 'format', 'validate', 'prettify', 'minify'],
    keywords: ['大括号', 'object', '对象', '压缩'],
    icon: 'Braces',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 预览',
    nameEn: 'Markdown Preview',
    description: '实时渲染 Markdown，支持 GFM、数学公式、代码高亮，导出 HTML',
    category: 'format',
    tags: ['markdown', 'preview', 'md', 'gfm', 'render'],
    keywords: ['md', '文档', '渲染'],
    icon: 'FileText',
  },

  // Encoding - 编码解码
  {
    id: 'base64',
    name: 'Base64 编解码',
    nameEn: 'Base64 Encoder/Decoder',
    description: '文本 Base64/Base64URL 编解码，支持文件转 Base64',
    category: 'encoding',
    tags: ['base64', 'encode', 'decode', 'base64url'],
    keywords: ['编码', '解码', '二进制'],
    icon: 'Binary',
  },
  {
    id: 'url-encode',
    name: 'URL 编解码',
    nameEn: 'URL Encoder/Decoder',
    description: 'encodeURIComponent/完整 URL 编解码，参数解析',
    category: 'encoding',
    tags: ['url', 'encode', 'decode', 'percent', 'uri'],
    keywords: ['链接', '参数', '转义'],
    icon: 'Link',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT 解析',
    nameEn: 'JWT Decoder',
    description: '解析 Header/Payload，时间戳转人类时间，高亮过期',
    category: 'encoding',
    tags: ['jwt', 'token', 'decode', 'auth', 'json web token'],
    keywords: ['令牌', '认证', '身份'],
    icon: 'KeyRound',
  },

  // Crypto - 加密安全
  {
    id: 'hash-calculator',
    name: 'Hash 计算器',
    nameEn: 'Hash Calculator',
    description: 'MD5/SHA-1/SHA-256/SHA-384/SHA-512 哈希计算，支持文本和文件',
    category: 'crypto',
    tags: ['hash', 'md5', 'sha', 'sha256', 'sha512', 'checksum'],
    keywords: ['哈希', '摘要', '校验'],
    icon: 'Hash',
  },

  // Generator - 生成器
  {
    id: 'uuid-generator',
    name: 'UUID 生成器',
    nameEn: 'UUID Generator',
    description: 'UUID v4 批量生成（最多1000），大写/小写/带连字符可选',
    category: 'generator',
    tags: ['uuid', 'generate', 'unique', 'id', 'guid', 'v4'],
    keywords: ['唯一', '标识符', 'GUID'],
    icon: 'Fingerprint',
  },
  {
    id: 'password-gen',
    name: '密码生成器',
    nameEn: 'Password Generator',
    description: '可配置字符集、长度、数量，强度可视化，批量导出',
    category: 'generator',
    tags: ['password', 'generate', 'random', 'secure', 'strong'],
    keywords: ['密码', '随机', '安全'],
    icon: 'KeySquare',
  },

  // Datetime - 时间日期
  {
    id: 'timestamp',
    name: '时间戳转换',
    nameEn: 'Timestamp Converter',
    description: 'Unix 时间戳与日期时间互转，支持毫秒/秒，全球时区',
    category: 'datetime',
    tags: ['timestamp', 'unix', 'datetime', 'timezone', 'convert'],
    keywords: ['时间', '日期', '时区'],
    icon: 'Clock',
  },

  // Text - 文本处理
  {
    id: 'case-converter',
    name: '命名规范转换',
    nameEn: 'Case Converter',
    description: 'camelCase/PascalCase/snake_case/kebab-case/CONSTANT 等互转',
    category: 'text',
    tags: ['case', 'camel', 'snake', 'pascal', 'kebab', 'convert'],
    keywords: ['大小写', '命名', '格式'],
    icon: 'CaseSensitive',
  },
  {
    id: 'lorem-ipsum',
    name: '占位文本生成',
    nameEn: 'Lorem Ipsum Generator',
    description: '英文 Lorem/中文乱数假文，段落数/单词数可配置',
    category: 'text',
    tags: ['lorem', 'ipsum', 'placeholder', 'dummy', 'text', '中文'],
    keywords: ['假文', '测试', '填充'],
    icon: 'AlignLeft',
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    nameEn: 'Regex Tester',
    description: '实时高亮匹配，分组提取，多行模式，常用正则库',
    category: 'text',
    tags: ['regex', 'regexp', 'test', 'match', 'pattern'],
    keywords: ['正则', '匹配', '模式'],
    icon: 'Regex',
  },
  {
    id: 'text-counter',
    name: '文本统计',
    nameEn: 'Text Counter',
    description: '字符数/单词数/行数/字节数/阅读时间估算',
    category: 'text',
    tags: ['text', 'count', 'character', 'word', 'line', 'byte'],
    keywords: ['统计', '字数', '计数'],
    icon: 'TextCursor',
  },

  // Color - 颜色设计
  {
    id: 'color-picker',
    name: '颜色选择器',
    nameEn: 'Color Picker',
    description: 'HEX/RGB/HSL/HSV/CMYK 互转，色盘可视化',
    category: 'color',
    tags: ['color', 'picker', 'hex', 'rgb', 'hsl', 'cmyk', 'convert'],
    keywords: ['颜色', '色彩', '调色'],
    icon: 'Palette',
  },

  // Converter - 单位换算
  {
    id: 'number-base',
    name: '进制转换',
    nameEn: 'Number Base Converter',
    description: '二/八/十/十六进制互转，按位操作可视化',
    category: 'converter',
    tags: ['binary', 'hex', 'octal', 'decimal', 'base', 'convert', 'radix'],
    keywords: ['二进制', '八进制', '十六进制'],
    icon: 'Binary',
  },

  // ─── Phase 2+: 后续阶段工具 ────────────────────────────────────────────────

  // Format - 格式化
  {
    id: 'yaml-json',
    name: 'YAML ↔ JSON',
    nameEn: 'YAML JSON Converter',
    description: 'YAML 与 JSON 格式互转',
    category: 'format',
    tags: ['yaml', 'json', 'convert'],
    icon: 'ArrowLeftRight',
  },
  {
    id: 'sql-formatter',
    name: 'SQL 格式化',
    nameEn: 'SQL Formatter',
    description: '格式化和美化 SQL 语句，支持多种数据库方言',
    category: 'format',
    tags: ['sql', 'format', 'database', 'mysql', 'postgresql'],
    icon: 'Database',
  },
  {
    id: 'xml-formatter',
    name: 'XML 格式化',
    nameEn: 'XML Formatter',
    description: '格式化、压缩、校验 XML 文档',
    category: 'format',
    tags: ['xml', 'format', 'validate', 'minify'],
    icon: 'Code2',
  },

  // Encoding - 编码解码
  {
    id: 'html-encode',
    name: 'HTML 实体编解码',
    nameEn: 'HTML Entity Encoder',
    description: 'HTML 实体编码与解码',
    category: 'encoding',
    tags: ['html', 'entity', 'encode', 'decode', 'escape'],
    icon: 'Code2',
  },
  {
    id: 'hex-encode',
    name: 'Hex 编解码',
    nameEn: 'Hex Encoder/Decoder',
    description: '文本与十六进制互转',
    category: 'encoding',
    tags: ['hex', 'encode', 'decode', 'hexadecimal'],
    icon: 'Hash',
  },
  {
    id: 'unicode-convert',
    name: 'Unicode 转换',
    nameEn: 'Unicode Converter',
    description: '字符与 Unicode 码点互转，支持多种表示格式',
    category: 'encoding',
    tags: ['unicode', 'utf', 'codepoint', 'convert'],
    icon: 'Languages',
  },
  {
    id: 'morse-code',
    name: '摩斯密码',
    nameEn: 'Morse Code',
    description: '文本与摩斯电码互转',
    category: 'encoding',
    tags: ['morse', 'code', 'encode', 'decode'],
    icon: 'Radio',
  },
  {
    id: 'binary-text',
    name: '二进制文本',
    nameEn: 'Binary Text',
    description: '文本与二进制字符串互转',
    category: 'encoding',
    tags: ['binary', 'text', 'encode', 'decode'],
    icon: 'Binary',
  },
  {
    id: 'rot13',
    name: 'ROT13/Caesar',
    nameEn: 'ROT13/Caesar Cipher',
    description: 'ROT13 及 Caesar 移位密码，偏移量可调',
    category: 'encoding',
    tags: ['rot13', 'caesar', 'cipher', 'encrypt'],
    icon: 'Lock',
  },
  {
    id: 'ascii-table',
    name: 'ASCII 码表',
    nameEn: 'ASCII Table',
    description: '完整 ASCII/Unicode 字符查询，支持描述搜索',
    category: 'encoding',
    tags: ['ascii', 'table', 'unicode', 'character'],
    icon: 'Table',
  },

  // Crypto - 加密安全
  {
    id: 'aes',
    name: 'AES 加密解密',
    nameEn: 'AES Encrypt/Decrypt',
    description: 'AES-GCM 对称加密与解密',
    category: 'crypto',
    tags: ['aes', 'encrypt', 'decrypt', 'crypto', 'symmetric'],
    icon: 'Lock',
  },
  {
    id: 'rsa-keygen',
    name: 'RSA 密钥生成',
    nameEn: 'RSA Key Generator',
    description: '生成 RSA 密钥对，导出 PEM 格式',
    category: 'crypto',
    tags: ['rsa', 'key', 'generate', 'pem', 'asymmetric'],
    icon: 'ShieldCheck',
  },
  {
    id: 'hmac',
    name: 'HMAC 计算',
    nameEn: 'HMAC Calculator',
    description: 'HMAC-SHA256/512 签名计算',
    category: 'crypto',
    tags: ['hmac', 'sha', 'signature', 'verify'],
    icon: 'KeyRound',
  },
  {
    id: 'ssh-keygen',
    name: 'SSH 密钥生成',
    nameEn: 'SSH Key Generator',
    description: '生成 Ed25519/RSA SSH 密钥对',
    category: 'crypto',
    tags: ['ssh', 'key', 'ed25519', 'rsa', 'generate'],
    icon: 'Terminal',
  },

  // Network - 网络HTTP
  {
    id: 'ip-lookup',
    name: 'IP 地址查询',
    nameEn: 'IP Lookup',
    description: '查询 IP 地址的地理位置、ASN 等信息',
    category: 'network',
    tags: ['ip', 'lookup', 'geo', 'asn', 'location'],
    icon: 'Globe',
    requiresApi: true,
  },
  {
    id: 'dns-lookup',
    name: 'DNS 查询',
    nameEn: 'DNS Lookup',
    description: '查询域名的 A、AAAA、MX、TXT、CNAME 记录',
    category: 'network',
    tags: ['dns', 'lookup', 'domain', 'mx', 'txt', 'cname'],
    icon: 'Search',
    requiresApi: true,
  },
  {
    id: 'url-parser',
    name: 'URL 解析',
    nameEn: 'URL Parser',
    description: '解析 URL 的各个组成部分',
    category: 'network',
    tags: ['url', 'parse', 'query', 'path', 'hostname'],
    icon: 'Unlink',
  },
  {
    id: 'http-status',
    name: 'HTTP 状态码',
    nameEn: 'HTTP Status Codes',
    description: '查询 HTTP 状态码的含义和说明',
    category: 'network',
    tags: ['http', 'status', 'code', '404', '500', '200'],
    icon: 'Activity',
  },
  {
    id: 'http-headers',
    name: 'HTTP 请求头',
    nameEn: 'HTTP Headers',
    description: '常见请求/响应头说明，安全头建议',
    category: 'network',
    tags: ['http', 'header', 'request', 'response'],
    icon: 'List',
  },
  {
    id: 'mime-types',
    name: 'MIME 类型',
    nameEn: 'MIME Types',
    description: '文件扩展名与 MIME 类型对照查询',
    category: 'network',
    tags: ['mime', 'type', 'extension', 'content-type'],
    icon: 'FileType',
  },
  {
    id: 'ip-subnet',
    name: 'IP 子网计算',
    nameEn: 'IP Subnet Calculator',
    description: 'CIDR 计算网络地址/广播地址/主机数',
    category: 'network',
    tags: ['ip', 'subnet', 'cidr', 'network', 'calculator'],
    icon: 'Network',
  },
  {
    id: 'user-agent',
    name: 'UA 解析',
    nameEn: 'User Agent Parser',
    description: '解析 User-Agent 字符串，识别浏览器/OS/设备',
    category: 'network',
    tags: ['user-agent', 'ua', 'browser', 'device', 'parse'],
    icon: 'Monitor',
  },
  {
    id: 'curl-converter',
    name: 'cURL 转换',
    nameEn: 'cURL Converter',
    description: 'cURL 命令转换为 fetch/axios/Python/Go 代码',
    category: 'network',
    tags: ['curl', 'convert', 'fetch', 'axios', 'python'],
    icon: 'Terminal',
  },

  // Text - 文本处理
  {
    id: 'text-diff',
    name: '文本 Diff',
    nameEn: 'Text Diff',
    description: '对比两段文本的差异，高亮显示',
    category: 'text',
    tags: ['diff', 'compare', 'text', 'difference'],
    icon: 'GitCompare',
  },
  {
    id: 'text-transform',
    name: '文本变换',
    nameEn: 'Text Transform',
    description: '去重/排序/反转/去空行/提取行等批量操作',
    category: 'text',
    tags: ['text', 'transform', 'sort', 'dedupe', 'reverse'],
    icon: 'TextCursorInput',
  },
  {
    id: 'string-escape',
    name: '字符串转义',
    nameEn: 'String Escape',
    description: 'JS/Python/Java/C 字符串转义与反转义',
    category: 'text',
    tags: ['string', 'escape', 'unescape', 'quote'],
    icon: 'Quote',
  },
  {
    id: 'cron-parser',
    name: 'Cron 表达式解析',
    nameEn: 'Cron Parser',
    description: '解析和生成 Cron 表达式，显示下次执行时间',
    category: 'text',
    tags: ['cron', 'schedule', 'parse', 'expression'],
    icon: 'Timer',
  },
  {
    id: 'text-similarity',
    name: '文本相似度',
    nameEn: 'Text Similarity',
    description: '计算两段文本的相似度，基于 Levenshtein 距离',
    category: 'text',
    tags: ['text', 'similarity', 'levenshtein', 'compare'],
    icon: 'GitCompare',
  },

  // Color - 颜色设计
  {
    id: 'color-converter',
    name: '颜色格式转换',
    nameEn: 'Color Converter',
    description: 'HEX、RGB、HSL、HSV、CMYK 颜色格式互转',
    category: 'color',
    tags: ['color', 'hex', 'rgb', 'hsl', 'hsv', 'cmyk', 'convert'],
    icon: 'Palette',
  },
  {
    id: 'gradient-generator',
    name: 'CSS 渐变生成器',
    nameEn: 'CSS Gradient Generator',
    description: '可视化生成 CSS 渐变代码',
    category: 'color',
    tags: ['gradient', 'css', 'linear', 'radial', 'color'],
    icon: 'Blend',
  },
  {
    id: 'color-palette',
    name: '配色方案生成',
    nameEn: 'Color Palette Generator',
    description: '输入主色生成类比/互补/三角配色方案',
    category: 'color',
    tags: ['color', 'palette', 'scheme', 'analogous', 'complementary'],
    icon: 'SwatchBook',
  },
  {
    id: 'contrast-checker',
    name: 'WCAG 对比度',
    nameEn: 'WCAG Contrast Checker',
    description: '前景/背景色对比度检测，AA/AAA 级别判定',
    category: 'color',
    tags: ['wcag', 'contrast', 'accessibility', 'color'],
    icon: 'Eye',
  },
  {
    id: 'color-blindness',
    name: '色盲模拟',
    nameEn: 'Color Blindness Simulator',
    description: '模拟 8 种色觉缺陷显示效果',
    category: 'color',
    tags: ['color', 'blindness', 'accessibility', 'simulate'],
    icon: 'Eye',
  },
  {
    id: 'tailwind-colors',
    name: 'Tailwind 色板',
    nameEn: 'Tailwind Colors',
    description: '完整 Tailwind v3/v4 色板，点击复制',
    category: 'color',
    tags: ['tailwind', 'color', 'palette', 'css'],
    icon: 'Palette',
  },
  {
    id: 'box-shadow',
    name: 'Box Shadow 生成',
    nameEn: 'Box Shadow Generator',
    description: '可视化调整 box-shadow，预览并复制 CSS',
    category: 'color',
    tags: ['css', 'shadow', 'box-shadow', 'generator'],
    icon: 'Square',
  },

  // Datetime - 时间日期
  {
    id: 'date-calc',
    name: '日期计算器',
    nameEn: 'Date Calculator',
    description: '日期加减/两日期差值，工作日计算',
    category: 'datetime',
    tags: ['date', 'calculator', 'diff', 'add', 'subtract'],
    icon: 'Calendar',
  },
  {
    id: 'timezone-convert',
    name: '时区转换',
    nameEn: 'Timezone Converter',
    description: '全球时区对照，多时区同屏显示',
    category: 'datetime',
    tags: ['timezone', 'convert', 'zone', 'utc'],
    icon: 'Globe',
  },
  {
    id: 'duration-format',
    name: '时长格式化',
    nameEn: 'Duration Formatter',
    description: '秒数与 hh:mm:ss/人话描述互转',
    category: 'datetime',
    tags: ['duration', 'format', 'time', 'convert'],
    icon: 'Timer',
  },
  {
    id: 'calendar-gen',
    name: '日历生成',
    nameEn: 'Calendar Generator',
    description: '生成指定年月日历，支持导出 iCal',
    category: 'datetime',
    tags: ['calendar', 'generate', 'ical', 'month'],
    icon: 'CalendarDays',
  },

  // Generator - 生成器
  {
    id: 'nanoid-gen',
    name: 'NanoID 生成器',
    nameEn: 'NanoID Generator',
    description: '自定义字符集和长度，批量生成',
    category: 'generator',
    tags: ['nanoid', 'generate', 'id', 'unique'],
    icon: 'Fingerprint',
  },
  {
    id: 'ulid-gen',
    name: 'ULID 生成器',
    nameEn: 'ULID Generator',
    description: '时间有序唯一 ID，比 UUID 更友好',
    category: 'generator',
    tags: ['ulid', 'generate', 'id', 'unique', 'time'],
    icon: 'Fingerprint',
  },
  {
    id: 'objectid-gen',
    name: 'MongoDB ObjectID',
    nameEn: 'MongoDB ObjectID Generator',
    description: '生成/解析 ObjectID，显示时间戳和机器码',
    category: 'generator',
    tags: ['objectid', 'mongodb', 'generate', 'parse'],
    icon: 'Fingerprint',
  },
  {
    id: 'faker-data',
    name: '假数据生成',
    nameEn: 'Fake Data Generator',
    description: '姓名/邮箱/手机/地址/公司等假数据生成',
    category: 'generator',
    tags: ['faker', 'fake', 'data', 'generate', 'mock'],
    icon: 'Database',
  },
  {
    id: 'qrcode',
    name: '二维码生成',
    nameEn: 'QR Code Generator',
    description: '生成二维码，支持文本、URL、WiFi 等格式',
    category: 'generator',
    tags: ['qrcode', 'qr', 'generate', 'barcode'],
    icon: 'QrCode',
  },
  {
    id: 'placeholder-img',
    name: '占位图生成',
    nameEn: 'Placeholder Image Generator',
    description: '生成指定尺寸/颜色/文字的占位图',
    category: 'generator',
    tags: ['placeholder', 'image', 'svg', 'generate'],
    icon: 'Image',
  },

  // Converter - 单位换算
  {
    id: 'exchange-rate',
    name: '汇率换算',
    nameEn: 'Exchange Rate',
    description: '实时汇率换算，支持全球主要货币',
    category: 'converter',
    tags: ['exchange', 'rate', 'currency', 'usd', 'cny'],
    icon: 'DollarSign',
    requiresApi: true,
    isNew: true,
  },
  {
    id: 'number-unit',
    name: '数字单位换算',
    nameEn: 'Number Unit Converter',
    description: '存储/速度/长度/重量/温度单位换算',
    category: 'converter',
    tags: ['unit', 'convert', 'storage', 'length', 'weight'],
    icon: 'Ruler',
  },
  {
    id: 'data-storage',
    name: '数据存储换算',
    nameEn: 'Data Storage Converter',
    description: 'KB/MB/GB/TB/PB，SI 与二进制单位互转',
    category: 'converter',
    tags: ['storage', 'convert', 'kb', 'mb', 'gb', 'tb'],
    icon: 'HardDrive',
  },

  // AI - AI增强
  {
    id: 'ai-code-explain',
    name: 'AI 代码解释',
    nameEn: 'AI Code Explainer',
    description: '用 AI 解释代码逻辑，支持多种编程语言',
    category: 'ai',
    tags: ['ai', 'code', 'explain', 'llm'],
    icon: 'Sparkles',
    requiresApi: true,
    isNew: true,
  },
  {
    id: 'ai-regex',
    name: 'AI 生成正则',
    nameEn: 'AI Regex Generator',
    description: '用自然语言描述，AI 生成对应的正则表达式',
    category: 'ai',
    tags: ['ai', 'regex', 'generate', 'natural language'],
    icon: 'Wand2',
    requiresApi: true,
    isNew: true,
  },
]

export const searchIndex = new Fuse(toolRegistry, {
  keys: [
    { name: 'name',        weight: 0.4 },
    { name: 'nameEn',      weight: 0.3 },
    { name: 'tags',        weight: 0.2 },
    { name: 'description', weight: 0.05 },
    { name: 'keywords',    weight: 0.05 },
  ],
  threshold: 0.35,
  includeScore: true,
})

export function searchTools(query: string): ToolMeta[] {
  if (!query.trim()) return toolRegistry
  return searchIndex.search(query).map(r => r.item)
}

export function getToolsByCategory(category: string): ToolMeta[] {
  return toolRegistry.filter(t => t.category === category)
}

export function getToolById(id: string): ToolMeta | undefined {
  return toolRegistry.find(t => t.id === id)
}
